apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: development
automountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-account-binding
  namespace: development
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: development
roleRef:
  kind: Role
  name: pod-reader # defined in roles.yml
  apiGroup: rbac.authorization.k8s.io